type tests.sll$SLL {
	next:tests.sll$SLL
	data:int
}
generateListWithLengthN(mut r3:tests.sll$SLL, mut $r1:tests.sll$SLL, mut $r2:tests.sll$SLL, mut i0:int, mut i1:int, mut r3.next:tests.sll$SLL) -> ($r1:tests.sll$SLL) {
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 1 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 1 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 1 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 1 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 1 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 1 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 1 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 1 && i1 == 1 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 2 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 2 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 2 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 2 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 2 && i1 == 2 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 3 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 3 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 3 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 3 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 3 && i1 == 3 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 4 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 4 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 4 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 4 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 4 && i1 == 4 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 5 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 5 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 5 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 5 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 5 && i1 == 5 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 6 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 6 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 6 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 6 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 6 && i1 == 6 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 7 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 7 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 7 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 7 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 7 && i1 == 7 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 8 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 8 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 8 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 8 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 8 && i1 == 8 && r3.next == sll0]
	}
	example {
		[r3 == null && $r1 == null && $r2 == null && i0 == 9 && i1 == 0 && r3.next == null]
		-> [r3 == null && $r1 == new tests.sll$SLL && $r2 == null && i0 == 9 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 9 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == null && i0 == 9 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 0 && r3.next == null]
		-> [r3 == $r1 && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 0 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 1 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 2 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 3 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 4 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 5 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 6 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 7 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 8 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 8 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 8 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 8 && r3.next == sll0]
		-> [r3 == r3.next && $r1 == new tests.sll$SLL && $r2 == new tests.sll$SLL && i0 == 9 && i1 == 9 && r3.next == sll0]
	}
}